version: "3"
services:
  soulseek:
    image: realies/soulseek
    container_name: soulseek
    restart: unless-stopped
    volumes:
      - /persistent/appdata:/data/.SoulseekQt
      - /home/mace/MUSICA:/persistent/downloads
      - /persistent/logs:/data/Soulseek Chat Logs
      - /home/mace/MUSICA:/persistent/shared
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - 6080:6080
      - 61122:61122 # example listening port, check Options -> Login
      - 61123:61123 # example obfuscated port, check Options -> Login
